### ISSUE TITLE
low speed

### ISSUE THREAD

**Issue by shahrokh451** [deathline94/sing-REALITY-Box#2]
thanks for the script. didnt work well for me. maybe operator restriction.i changed SNI multiple times , still had low speed

**Comment by deathline94** [comment]
best i can tell , your ip got flagged/blacklisted . cause this script uses the most common configs for REALITY, nothing more.
my advice , buy vps from Amazon or azure for the best results

**Comment by shahrokh451** [comment]
thanks a million



Sent from my Galaxy



-------- Original message --------
From: deathline94 ***@***.***>
Date: 5/18/23 22:43 (GMT+03:30)
To: deathline94/sing-REALITY-Box ***@***.***>
Cc: shahrokh451 ***@***.***>, Author ***@***.***>
Subject: Re: [deathline94/sing-REALITY-Box] low speed (Issue #2)


best i can tell , your ip got flagged/blacklisted . cause this script uses the most common configs for REALITY, nothing more.
my advice , buy vps from Amazon or azure for the best results

**Comment by deathline94** [comment]
<3

**Comment by shahrokh451** [comment]
why your page not found in github?



Sent from my Galaxy



-------- Original message --------
From: deathline94 ***@***.***>
Date: 5/19/23 00:16 (GMT+03:30)
To: deathline94/sing-REALITY-Box ***@***.***>
Cc: shahrokh451 ***@***.***>, Author ***@***.***>
Subject: Re: [deathline94/sing-REALITY-Box] low speed (Issue #2)


<3

**Comment by shahrokh451** [comment]
ok i got it.

now let me know can i run this script in my server installed with another xui script? no interfer? or a way to uninstall?



Sent from my Galaxy



-------- Original message --------
From: deathline94 ***@***.***>
Date: 5/19/23 00:16 (GMT+03:30)
To: deathline94/sing-REALITY-Box ***@***.***>
Cc: shahrokh451 ***@***.***>, Author ***@***.***>
Subject: Re: [deathline94/sing-REALITY-Box] low speed (Issue #2)


<3

**Comment by shahrokh451** [comment]
bash <(curl -fsSL https://raw.githubusercontent.com/namelesghoul/sing-box-REALITY/main/sing-box-REALITY.sh)uninstall   ?
or


Uninstall Sing-Box and remove all associated files   ?
________________________________
