### ISSUE TITLE
تفاوت اسکریپ با نسخه namelesghoul

### ISSUE THREAD

**Issue by techjoyment** [deathline94/sing-REALITY-Box#3]
سلام. ممنون بابت اسکریپ خوبتون
فرق این اسکریپ با این مورد چی هست؟ https://github.com/namelesghoul/sing-box-REALITY

**Comment by deathline94** [comment]
سلام . هر دو یک نسخه هستند . در دو ریپو متفاوت آپلود شدند محض بکاپ و احتیاط
