### ISSUE TITLE
کار نمیکنه روی رایتل

### ISSUE THREAD

**Issue by techjoyment** [deathline94/sing-REALITY-Box#7]
ورژن اولیه رو که داده بودی خیلی عالی کار میکرد. سرور رو مجبور شدم پاک کنم و دوباره نصب کردم دیگه کار نکرد. میشه ورژن قبلی رو داشت؟

**Comment by deathline94** [comment]
فرق ورژن قبلی با این یکی فقط در بعضی اصلاحات نگارشی و باگ های خیلی جزئی هست . تاثیری روی راندمان کلی کار ندارد . متاسفانه در مورد کار کردن/نکردن روی اینترنت به خصوص , مشکل از آی پی سرور هست که احتمالا روی رایتل فیلتر شده . وگرنه برنامه و اسکریپت خیلی کلی هست و چیزهایی مثل سرعت و پینگ و قطعی وصلی به سرور تون برمیگرده

**Comment by techjoyment** [comment]
با اسکریپت reality-ezpz کار کرد. فیلتر نیست سرور من.
