### ISSUE TITLE
Install script cannot install sing-box RC.1

### ISSUE THREAD

**Issue by OnceUponATimeInAmerica** [deathline94/sing-REALITY-Box#8]
Due to [this line](https://github.com/deathline94/sing-REALITY-Box/blob/8bae6885f7e662accf601c22b59a328338062f00/sing-REALITY-box.sh#L214)  in the install script, with the RC version of the sing-box core, the install script cannot correctly find, download and thus install the core and so it fails!

**Comment by deathline94** [comment]
Seems like the sagernet/sing-box team don't know the first things about URL schemes, as they change them randomly, hence the error in the script when it tries to fetch the latest version. Let me take a look and it will be fixed soon. A screenshot of the error lines is appreciated, nevertheless.

**Comment by deathline94** [comment]
Fixed !! @SagerNet. Please make the naming of your releases more consistent !
